server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/btp_management
spring.datasource.username=postgres
spring.datasource.password=123456

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

app.jwt.secret=YnRwLW1hbmFnZW1lbnQtc3VwZXItc2VjcmV0LWtleS1mb3ItanN0LTI1Ng==
app.jwt.expiration-ms=86400000
